version: '3.1'

services:
  world_db:
    container_name: world_db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: "world"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"